name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: cmake -G "Visual Studio 17 2022" -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_ZLIB=ON -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF

    - name: Build and Install
      run: cmake --build ${{ github.workspace }}/build --target install --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assimp-release
        path: ${{ github.workspace }}/install/*
